context:
  name: dedupe
  version: "3.0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/35/ae/5f1e4c26ad724246be6a63a50a21527a47d32f7a878b16724fef26eec205/${{ name }}-${{ version }}.tar.gz
  sha256: d2ac91e14a2b873481da9917ee1b154f53d760326e1a47bce9bcb044eb884314 

build:
  number: 0
  script: python -m pip install . -vv
#  script: {{ PYTHON }} -m pip install . -vv
#  skip: true  # [win]

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  host:
    - cython
    - pip
    - python
    - setuptools
    - wheel
  run:
    - scikit-learn
    - affinegap >=1.3
    - btrees >=4.1.4
    - categorical-distance >=1.9
    - doublemetaphone
    - haversine >=0.4.1
    - highered >=0.2.0
    - levenshtein-search
    - numpy >=1.20
    - python
    - simplecosine >=1.2
    - zope.index

tests:
  - python:
      imports:
      - dedupe
      - dedupe.variables
      pip_check: true

about:
  homepage: https://github.com/dedupeio/dedupe
  summary: A python library for accurate and scaleable data deduplication and entity-resolution
  license: MIT
  license_file: LICENSE
  repository: https://github.com/dedupeio/dedupe

extra:
  recipe-maintainers:
    - osamples
    - izahn
